module Neuz
  module Prompts
    module_function

    # Only ONE prompt is surfaced to the user: the interview prompt. The
    # recurring prompt is generated by Claude during the interview, but we
    # ship a reference template (`prompts/recurring.md`) that gets inlined
    # into the interview prompt so Claude has a concrete shape to model on.
    # The user never sees the template as a separate copy-paste block.
    def interview(url:, api_key:)
      recurring_template = render("recurring.md", url, api_key)
      render("interview.md", url, api_key)
        .gsub("{{RECURRING_TEMPLATE}}", recurring_template)
    end

    def render(template, url, api_key)
      path = File.join(Config.prompts_dir, template)
      File.read(path)
        .gsub("{{NEUZ_URL}}", url.to_s)
        .gsub("{{NEUZ_API_KEY}}", api_key.to_s)
    end
  end
end
